// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.3
// source: open_tracer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *TraceInfo) Reset() {
	*x = TraceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_tracer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceInfo) ProtoMessage() {}

func (x *TraceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_open_tracer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceInfo.ProtoReflect.Descriptor instead.
func (*TraceInfo) Descriptor() ([]byte, []int) {
	return file_open_tracer_proto_rawDescGZIP(), []int{0}
}

func (x *TraceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Material struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Pids []string `protobuf:"bytes,2,rep,name=pids,proto3" json:"pids,omitempty"`
}

func (x *Material) Reset() {
	*x = Material{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_tracer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_open_tracer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_open_tracer_proto_rawDescGZIP(), []int{1}
}

func (x *Material) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Material) GetPids() []string {
	if x != nil {
		return x.Pids
	}
	return nil
}

type BillOfMaterials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Materials []*Material `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
}

func (x *BillOfMaterials) Reset() {
	*x = BillOfMaterials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_tracer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillOfMaterials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillOfMaterials) ProtoMessage() {}

func (x *BillOfMaterials) ProtoReflect() protoreflect.Message {
	mi := &file_open_tracer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillOfMaterials.ProtoReflect.Descriptor instead.
func (*BillOfMaterials) Descriptor() ([]byte, []int) {
	return file_open_tracer_proto_rawDescGZIP(), []int{2}
}

func (x *BillOfMaterials) GetMaterials() []*Material {
	if x != nil {
		return x.Materials
	}
	return nil
}

type TraceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid string `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *TraceInfoRequest) Reset() {
	*x = TraceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_tracer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceInfoRequest) ProtoMessage() {}

func (x *TraceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_open_tracer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceInfoRequest.ProtoReflect.Descriptor instead.
func (*TraceInfoRequest) Descriptor() ([]byte, []int) {
	return file_open_tracer_proto_rawDescGZIP(), []int{3}
}

func (x *TraceInfoRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

var File_open_tracer_proto protoreflect.FileDescriptor

var file_open_tracer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x72,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f,
	0x0a, 0x09, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x32, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x69, 0x64, 0x73, 0x22, 0x46, 0x0a, 0x0f, 0x42, 0x69, 0x6c, 0x6c, 0x4f, 0x66, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x52, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x24, 0x0a, 0x10, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69,
	0x64, 0x32, 0xd4, 0x01, 0x0a, 0x10, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x65, 0x6e,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x30, 0x01, 0x12,
	0x41, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x4f, 0x66, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x72, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x4f, 0x66, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x73, 0x12, 0x34, 0x0a, 0x14, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x42, 0x69, 0x6c, 0x6c, 0x4f,
	0x66, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x65, 0x70, 0x66, 0x65, 0x6e, 0x63, 0x65,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_open_tracer_proto_rawDescOnce sync.Once
	file_open_tracer_proto_rawDescData = file_open_tracer_proto_rawDesc
)

func file_open_tracer_proto_rawDescGZIP() []byte {
	file_open_tracer_proto_rawDescOnce.Do(func() {
		file_open_tracer_proto_rawDescData = protoimpl.X.CompressGZIP(file_open_tracer_proto_rawDescData)
	})
	return file_open_tracer_proto_rawDescData
}

var file_open_tracer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_open_tracer_proto_goTypes = []interface{}{
	(*TraceInfo)(nil),        // 0: open_tracer.TraceInfo
	(*Material)(nil),         // 1: open_tracer.Material
	(*BillOfMaterials)(nil),  // 2: open_tracer.BillOfMaterials
	(*TraceInfoRequest)(nil), // 3: open_tracer.TraceInfoRequest
	(*Empty)(nil),            // 4: common.Empty
}
var file_open_tracer_proto_depIdxs = []int32{
	1, // 0: open_tracer.BillOfMaterials.materials:type_name -> open_tracer.Material
	3, // 1: open_tracer.KernelOpenTracer.GetTraceInfo:input_type -> open_tracer.TraceInfoRequest
	4, // 2: open_tracer.KernelOpenTracer.GetBillOfMaterials:input_type -> common.Empty
	4, // 3: open_tracer.KernelOpenTracer.ClearBillOfMaterials:input_type -> common.Empty
	0, // 4: open_tracer.KernelOpenTracer.GetTraceInfo:output_type -> open_tracer.TraceInfo
	2, // 5: open_tracer.KernelOpenTracer.GetBillOfMaterials:output_type -> open_tracer.BillOfMaterials
	4, // 6: open_tracer.KernelOpenTracer.ClearBillOfMaterials:output_type -> common.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_open_tracer_proto_init() }
func file_open_tracer_proto_init() {
	if File_open_tracer_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_open_tracer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_tracer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Material); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_tracer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillOfMaterials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_tracer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_open_tracer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_open_tracer_proto_goTypes,
		DependencyIndexes: file_open_tracer_proto_depIdxs,
		MessageInfos:      file_open_tracer_proto_msgTypes,
	}.Build()
	File_open_tracer_proto = out.File
	file_open_tracer_proto_rawDesc = nil
	file_open_tracer_proto_goTypes = nil
	file_open_tracer_proto_depIdxs = nil
}
